minor changes to config files
adonisjs/adonis-app pull request #46
Opened 2016-11-20 19:55 UTC by ctf0

1- changed some security settings to make it as more secure out of the
box
2- changed the data-upload limit for something more reasonable
3- added an env key for SESSION_DOMAIN for easier user exp
4- fixed some docs typos and made config files more consistent
5- added PATCH verb to csrf

2016-11-20 20:34 UTC, RomainLanz commented
Nice one !

2016-11-20 20:34 UTC, RomainLanz approved these changes

2016-11-20 20:57 UTC, ctf0 commented
i will update the docs once the PR is merged.

2016-11-24 22:25 UTC, RomainLanz requested changes

2016-11-24 22:25 UTC, RomainLanz commented on .env.example
> +DB_CONNECTION=mysql
We should keep sqlite

2016-11-24 22:25 UTC, RomainLanz commented on .env.example
> +DB_PORT=3306
This is the default port

2016-11-24 22:25 UTC, RomainLanz commented on config/database.js
> +  | Drivers
Why?

2016-11-24 22:25 UTC, RomainLanz commented on config/database.js
> -  */
Why?

2016-11-24 22:25 UTC, RomainLanz commented on config/database.js
> +  maria: {
It's the same as mysql

2016-11-24 22:25 UTC, RomainLanz commented on config/database.js
> -  */
Why?

2016-11-24 22:57 UTC, ctf0 commented on .env.example
> +DB_CONNECTION=mysql
the reason i changed because most of ppl use mysql and to also keep the db env keys unless the user wants to use sqlite then he can remove them

2016-11-24 22:58 UTC, ctf0 commented on .env.example
> +DB_PORT=3306
yes but sometimes the user use a different one, so its kept just incase

2016-11-24 22:59 UTC, ctf0 commented on config/database.js
> +  | Drivers
because from the docs, some dbs have more than one driver, so its left for the user to decide which driver he wants to install/use

2016-11-24 23:00 UTC, ctf0 commented on config/database.js
> +  maria: {
i know, but i added as it was mentioned in the docs, so i thought maybe there is something different

2016-11-25 07:56 UTC, RomainLanz commented on .env.example
> +DB_CONNECTION=mysql
SQLite driver can works without installing anything (only the sqlite package). That's why it is use by default.

2016-11-25 13:55 UTC, ctf0 commented on .env.example
> +DB_CONNECTION=mysql
no problem, we can change it back then

2016-11-25 14:09 UTC, RomainLanz requested changes

2016-11-25 14:09 UTC, RomainLanz commented on bootstrap/app.js
> +  'App/Commands/Greet',
This is an example command, it should stick to the top to be removed easily.

2016-11-25 14:11 UTC, ctf0 commented on bootstrap/app.js
> +  'App/Commands/Greet',
will keep it along with greet at the top then

2016-11-25 14:26 UTC, RomainLanz commented
I'll let @thetutlage review it and react to changes.

2016-11-25 14:32 UTC, ctf0 commented
@RomainLanz btw,if i've a couple of ideas what is the best place to put ? i dont think issuing a ticket on the main repo is the correct action

2016-11-25 14:34 UTC, RomainLanz commented
You should use the https://github.com/adonisjs/discussion repository.

2016-11-28 08:15 UTC, thetutlage reviewed
@ctf0 Their are some reviews, please look into them so that I can merge the PR

2016-11-28 08:15 UTC, thetutlage commented on config/bodyParser.js
> +  limit: '125mb',
125MB for post data is too much. This does not include file uploads and should be under `20MB`. If someone has requirements they should come and toggle this value, atleast with that they would know what they are doing.

2016-11-28 16:25 UTC, ctf0 commented on config/bodyParser.js
> +  limit: '125mb',
okay no problem

2016-12-01 09:27 UTC, thetutlage commented on .env.example
> +SESSION_COOKIE=example-session
Session cookie does not needs to be here. Neither the session domain. 

I will never change the `cookie` name for each environment. Also their should be `DOMAIN` variable, which can be used by application internally and should not be part of core

2016-12-01 19:09 UTC, ctf0 commented on .env.example
> +SESSION_COOKIE=example-session
the reason behind `SESSION_COOKIE & SESSION_DOMAIN` is to minimize being effected by any bug that could be used by an attacker.

2017-01-18 17:02 UTC, thetutlage commented
This PR has lot of stuff going. I would suggest to split into multiple PR's

2017-01-18 17:02 UTC, closed without merging